name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      name: 'Checkout'
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
      name: 'Setup .NET Core 3.1.x'
    - run: |
        dotnet restore
        dotnet build --no-restore --configuration Release
        dotnet test Tests.csproj --no-build --configuration Release
        mkdir ${{ github.workspace }}
        dotnet pack --no-build -c Release --output "${{ github.workspace }}"
    - uses: actions/upload-artifact@v1
      with:
        name: Artifact upload
        path: ${{ github.workspace }}
