name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install dependencies
    - run: |
        dotnet restore
        dotnet build --no-restore --configuration Release
        dotnet test Tests.csproj --no-build --configuration Release
        mkdir ${{ github.workspace }}
        dotnet pack --no-build -c Release --output "${{ github.workspace }}"
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v2
      with:
          name: dotnet-results-${{ matrix.dotnet-version }}
          path: ${{ github.workspace }}
      if: ${{ always() }}
